# COMPONENT CONSTANTS

COMP_TRANSFORM = 0
TRANSFORM_X = 0
TRANSFORM_Y = 1
TRANSFORM_Z = 2
TRANSFORM_RX = 3
TRANSFORM_RY = 4
TRANSFORM_RZ = 5
TRANSFORM_RA = 6
TRANSFORM_SX = 7
TRANSFORM_SY = 8
TRANSFORM_SZ = 9

# SIZE INFORMATION

COMP_SIZES = [10]
COMP_COUNT = 1
ENTITY = COMP_COUNT
