# COMPONENT CONSTANTS

COMP_TRANSFORM = 0
TRANSFORM_X = 2
TRANSFORM_Y = 3
TRANSFORM_Z = 4
TRANSFORM_PITCH = 5
TRANSFORM_YAW = 6
TRANSFORM_SX = 7
TRANSFORM_SY = 8
TRANSFORM_SZ = 9

COMP_CAMERA = 1
CAMERA_FOV = 2
CAMERA_NEAR = 3
CAMERA_FAR = 4

COMP_MESH = 2
MESH_ID = 2
MESH_SPEC_R = 3
MESH_SPEC_G = 4
MESH_SPEC_B = 5

COMP_INPUT = 3
INPUT_ID = 2

COMP_PLAYER = 4
PLAYER_ACCEL_FORCE = 2
PLAYER_ACCEL_INPUT = 3

COMP_SHAPE = 5
SHAPE_ID = 2
SHAPE_DX = 3
SHAPE_DY = 4
SHAPE_DA = 5
SHAPE_TYPE = 6
SHAPE_MASS = 7
SHAPE_RADIUS = 8
SHAPE_SIZE_X = 9
SHAPE_SIZE_Y = 10
SHAPE_ELASTICITY = 11
SHAPE_FRICTION = 12

# SIZE INFORMATION

COMP_SIZES = [8, 3, 4, 1, 2, 11]
COMP_COUNT = 6
ENTITY = COMP_COUNT
